### PR TITLE
CSIP65 testcase.xml

### PR DESCRIPTION
**Pull request by PhillipTommerholt**
Updated testCase.xml. 1 rule and 3 packages

### CODE REVIEW

**Review by PhillipTommerholt — COMMENTED** [review]
mistyped - CSIP75 = CSIP65

**Comment by koit** [comment]
The csip/fileSec/csip65 branch currently has a conflict with the following history.

1. csip/fileSec/csip66 branch had an accidental edit of corpora/csip/metadata/filesec/CSIP65/testCase.xml
2. I deleted that file from csip66 branch (thinking that it will only disappear from the csip66 branch)
3. I merged csip/fileSec/csip66 to integration, resulting in corpora/csip/metadata/filesec/CSIP65/testCase.xml getting deleted from integration
4. csip/fileSec/csip65 branch is now in conflict with integration regarding that file.

I tried to resolve the conflict using the steps given by GitHub:
```
git fetch origin
git checkout -b csip/fileSec/csip65 origin/csip/fileSec/csip65
git merge integration
git checkout integration
git merge --no-ff csip/fileSec/csip65
git push origin integration
```
This fails, because merges to integration have to get an approving review, but there is no way to create a pull request for a push operation.

**Comment by koit** [comment]
#132

**Review by koit — APPROVED** [review]

**Comment by koit** [comment]
Got it fixed now:
```
git fetch origin
git checkout -b csip/filesec/csip65 origin/csip/fileSec/csip65
git merge integration
git add csip/metadata/filesec/CSIP65/testCase.xml
git commit
git push origin HEAD:csip/fileSec/csip65
```
It turned out Github's instructions were too complicated.

**Pull request merged**
