### PR TITLE
Create minimal_IP_with_1_representation

### PR DESCRIPTION
**Pull request by koit**
To my knowledge, this IP is valid (I went through all the relevant requirements and fixed several issues that were present in the previous template IPs). Some problems remain, as CSIP is not clear on representation METS files, incl.:

- CSIP104 `structMap/div/div/@CONTENTID`, see https://github.com/DILCISBoard/E-ARK-CSIP/issues/317;
- CSIP109 `structMap/div/div/mptr` produces a circular reference to itself;
- The whole discussion on whether there is a mandatory folder structure has a lot of implications on this IP.

However, for the time being I think we could use this IP in the corpus.

### CODE REVIEW

**Review by PhillipTommerholt — DISMISSED** [review]
Generally it looks good.
I am not sure what the purpose of this IP is, though? I would suspect that a representation has data in it, if it doesn't then it is not really a representation.

**Comment by koit** [comment]
Thanks, Phillip! I was so caught up in technical details that I didn't notice the obvious. For my initial case with `mets/@OBJID` the data file was not needed, but this is probably the only use for such artificial package. I have now added a data file, so the IP should be usable in other cases, too.

**Review by PhillipTommerholt — CHANGES_REQUESTED** [review]
Here are some of my observations.

1) I don't see the "plain_text_document.txt" in the rep1/data folder?
2) I think the correct csip:CONTENTINFORMATIONTYPE should have the value "OTHER" and with another attribute OTHERCONTENTINFORMATIONTYPE describing the data file. 
2a) CSIP thoughts: I think it is strange that the OTHER value must be described in another attribute, whereas the "MIXED" need no further explanation... should we take this to the A2 group?
3) I like the values in the USE-attribute. The CSIP is not clear about this, but I like that the root METS.xml in your example has the value "representations/rep1" and the representation METS.xml has the value "representations/rep1/data". Maybe that it is how it is meant to be in the current CSIP but I know that it is under revision https://github.com/DILCISBoard/E-ARK-CSIP/issues/404  
4)  The root METS file metadata for the representation METS seem to have wrong file size and MD5 sum?

**Comment by koit** [comment]
I went through the spec line-by-line and updated the package accordingly. I believe it is now compliant with CSIP v.2.0.3.

Regarding Phillip's remark that ``@csip:CONTENTINFORMATIONTYPE`` should have the value "OTHER" - I agree, it would make more sense but I didn't change it because that would add complexity in the form of ``@csip:OTHERCONTENTINFORMATIONTYPE`` attribute. The aim with this IP is simplicity and formal compliance, while the actual content is artificial, so the difference between OTHER and MIXED is not important.

**Review by PhillipAasvangTommerholt — APPROVED** [review]

**Pull request closed without merging**
