### PR TITLE
CSIP19 - created corpora package and testCase.xml

### PR DESCRIPTION
**Pull request by PhillipTommerholt**
created 1 corpora package and 1 testCase.xml and added 1 testCase.xsd

### CODE REVIEW

**Comment by carlwilson** [comment]
Fixed conflicts in preparation for merge.

**Review by carlwilson — CHANGES_REQUESTED** [review]
Just note in the description what we're NOT carrying out in terms of date sanity checking.

**Comment by andersbonielsen** [comment]
PhillipTommerholt requested a review from @carlwilson 21 days ago
Since Phillip specificly request Carl to review this I will skip this and move on to the next pull request that I am a requested reviewer for.

**Review by andersbonielsen — COMMENTED** [review]
Fine with me, we just need @carlwilson Carl to approve this one as req. by Phillip

**Review by carlwilson — APPROVED** [review]

**Pull request merged**
